# 2015-09-12  William A. Hudson

# Run all test suites.

PATH = /usr/bin:/bin

SHELL = /bin/sh

test:
	cd t_rgAddrMap        && make test
	cd t_rgClk            && make test
	cd t_rgClock          && make test
	cd t_rgFselPin        && make test
	cd t_rgIoPin          && make test
	cd t_rgPwm            && make test
	cd t_rgRegister       && make test
	cd t_rgSpi0           && make test
	cd t_rgUniSpi         && make test
#	cd t_utLib1           && make test

clean:
	cd t_rgAddrMap        && make clean
	cd t_rgClk            && make clean
	cd t_rgClock          && make clean
	cd t_rgFselPin        && make clean
	cd t_rgIoPin          && make clean
	cd t_rgPwm            && make clean
	cd t_rgRegister       && make clean
	cd t_rgSpi0           && make clean
	cd t_rgUniSpi         && make clean
#	cd t_utLib1           && make clean

