# 2015-09-12  William A. Hudson

# Run all test suites.

PATH = /usr/bin:/bin

SHELL = /bin/sh

test:
	cd t_Error            && make test
	cd t_clock            && make test
	cd t_fsel             && make test
	cd t_io               && make test
	cd t_rgpio            && make test
	cd t_yUtil            && make test

clean:
	cd t_Error            && make clean
	cd t_clock            && make clean
	cd t_fsel             && make clean
	cd t_io               && make clean
	cd t_rgpio            && make clean
	cd t_yUtil            && make clean

