# 2015-09-12  William A. Hudson

# Run all test suites.

PATH = /usr/bin:/bin

SHELL = /bin/sh

test:
	cd t_Error            && make test
	cd t_rgAddrMap        && make test
	cd t_rgClock          && make test
	cd t_rgFselPin        && make test
	cd t_rgIoPin          && make test
#	cd t_utLib1           && make test

clean:
	cd t_Error            && make clean
	cd t_rgAddrMap        && make clean
	cd t_rgClock          && make clean
	cd t_rgFselPin        && make clean
	cd t_rgIoPin          && make clean
#	cd t_utLib1           && make clean

